services:
  - type: web
    name: mammogram-classifier
    env: python
    buildCommand: |
      pip install --upgrade pip
      pip install -r requirements.txt
      python manage.py collectstatic --noinput
      python manage.py migrate
    startCommand: gunicorn mammogram_project.wsgi:application
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: mammogram_project.settings
      - key: DEBUG
        value: False
      - key: RENDER
        value: True

